---
- name: CREATE ELASTICSEARCH SERVICE FILE
  template:
    src: elasticsearch.service
    dest: /etc/systemd/system/elasticsearch.service
- name: CREATE ELASTICSEARCH DIRECTORIES
  file:
    path: "{{ item.value }}"
    state: directory
  with_dict: "{{ es_path }}"
- name: CREATE ELASTICSEARCH CONFIGURATION FILES
  template:
    src: "{{ item }}"
    dest: "{{ es_path.conf }}/{{ item }}"
  with_items:
    - elasticsearch.yml
- name: docker compose elasticsearch
  copy:
    src: "../templates/docker-compose.yml"
    dest: "/tmp/docker-compose.yml"
- name: create service with docker-compose
  shell: "docker stack deploy --compose-file=/tmp/docker-compose.yml elastic"